name: 🍏 iOS Builds
on:
  push:
    branches: [ master, add-github-actions ]

# Global Settings
env:
  TARGET: release
  FMOD_EXECUTABLE: fmodstudioapi20002ios.dmg

jobs:
  ios-compilation:
    name: iOS Compilation
    runs-on: "macos-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # You can test your matrix by printing the current Python version
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons requests
          python --version
          scons --version

      - name : Installing FMOD
        run: |
          mkdir libs && cd libs
          mkdir fmod && cd fmod
          python ../../get_fmod.py ${{secrets.FMODUSER}} ${{secrets.FMODPASS}} ios
          hdiutil attach ${{env.FMOD_EXECUTABLE}}
          cp -r "/Volumes/FMOD Programmers API iOS/FMOD Programmers API/api" ios
          cd ../../

      - name: Cloning godot-cpp
        uses: actions/checkout@v2
        with:
          repository: utopia-rise/godot-cpp
          path: godot-cpp
          ref: utopia-3.2
          submodules: recursive

      - name: Compilation
        run: |
          cd godot-cpp
          scons platform=ios ios_arch=armv7 bits=64 target=${{env.TARGET}} generate_bindings=yes -j4
          scons platform=ios ios_arch=arm64 bits=64 target=${{env.TARGET}} generate_bindings=yes -j4
          cd ..
          scons platform=ios ios_arch=armv7 target=${{env.TARGET}} cpp_bindings_dir=godot-cpp/ fmod_lib_dir=libs/fmod/
          scons platform=ios ios_arch=arm64 target=${{env.TARGET}} cpp_bindings_dir=godot-cpp/ fmod_lib_dir=libs/fmod/

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ios
          path: bin
